require('jquery');
require('jquery-ui');
require('../css/index.css');
require('../css/creative.css');
require('../css/animate.min.css');
require('bootstrap-webpack');
require('classie');
require('../externals/creative.js');
require('../externals/wow.min.js')
require('font-awesome-webpack');